bus: add AccessBeyondPeripheral error kind
ConchuOD/thing pull request #5
Opened 2023-05-23 10:10 UTC by JSchrtke

2023-05-23 17:51 UTC, ConchuOD requested changes
Could you please add a SoB to the commit? (git commit --amend -s)

2023-05-23 17:51 UTC, ConchuOD commented on bus/mod.rs
> +	AccessBeyondPeripheral,
What about OutOfBounds?

2023-05-23 17:51 UTC, ConchuOD requested changes
Could you please add a SoB to the commit? (git commit --amend -s)

2023-05-23 20:02 UTC, merged

2023-05-24 07:32 UTC, JSchrtke commented on bus/mod.rs
> +	AccessBeyondPeripheral,
Sorry, didn't see this yesterday. I used your original suggestion. Does out of bounds make more sense in the context of the bus?

2023-05-24 14:30 UTC, ConchuOD commented on bus/mod.rs
> +	AccessBeyondPeripheral,
> Sorry, didn't see this yesterday. I used your original suggestion. Does out of bounds make more sense in the context of the bus?

It just makes it more general I guess, since "BeyondPeripheral" basically means OutOfBounds, but it could also mean reading from a location that is forbidden.